#!/usr/bin/env bash
# Typeshare drift gate — fails if swift-bridge-generated shims in
# $REPO/app/NextTerm/Generated/ have drifted from what
# `cargo build --workspace` would produce right now.
#
# Salvages the zenzai-v2 typeshare-drift-gate pattern (`427d7b3`) per
# the 2026-04-22 postmortem: "CI fails if `#[typeshare]`-annotated
# Rust types in `zenzai-ipc` drift from the Swift mirror. Solves the
# silent-wire-divergence class of bugs."
#
# Same idea here, swift-bridge edition. The Generated/ Swift + C shims
# are committed to the repo so AppKit/Xcode builds without invoking
# Cargo first. Without a drift gate, an FFI change to bridge.rs that
# forgets to re-commit the regenerated Swift shim ships as compile-OK
# locally (build-rust.sh runs first) but breaks fresh-clone /
# downstream consumers — and is the exact class of bug the v2
# build_snapshot stub demonstrated (parser + renderer both "looked
# right" with a stub between them).
#
# Usage:
#   scripts/check-ffi-drift.sh         # CI: fail on drift
#   scripts/check-ffi-drift.sh --fix   # local: regenerate + commit

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

FIX_MODE=0
if [[ "${1:-}" == "--fix" ]]; then
    FIX_MODE=1
fi

GEN_DIR="$REPO_ROOT/app/NextTerm/Generated"
SHIMS=(
    "SwiftBridgeCore.swift"
    "SwiftBridgeCore.h"
    "nextterm_ffi.swift"
    "nextterm_ffi.h"
)

echo "▶ cargo build --workspace (regenerates swift-bridge shims)"
cargo build --workspace --quiet

# Locate the freshly-regenerated shims under target/.../build/nextterm-ffi-*/out/
OUT_DIR=$(find target/debug/build \
    -maxdepth 2 -type d -name "out" -path "*nextterm-ffi*" \
    -print -quit 2>/dev/null || true)
if [[ -z "$OUT_DIR" ]]; then
    echo "error: could not locate swift-bridge OUT_DIR under target/debug/build" >&2
    exit 1
fi

drift_found=0
for shim in "${SHIMS[@]}"; do
    # Mirror build-rust.sh's source layout — top-level shims sit
    # directly under OUT_DIR; per-crate shims live in a subdir matching
    # the crate name.
    case "$shim" in
        SwiftBridge*) src="$OUT_DIR/$shim" ;;
        *) src="$OUT_DIR/nextterm_ffi/$shim" ;;
    esac
    dst="$GEN_DIR/$shim"

    if [[ ! -f "$src" ]]; then
        echo "error: swift-bridge didn't emit $src" >&2
        exit 1
    fi

    if [[ ! -f "$dst" ]] || ! cmp -s "$src" "$dst"; then
        drift_found=1
        echo "✗ DRIFT: $shim"
        if [[ $FIX_MODE -eq 1 ]]; then
            cp "$src" "$dst"
            echo "  → regenerated"
        else
            echo "  generated bytes differ from $dst"
            echo "  run: scripts/check-ffi-drift.sh --fix"
        fi
    fi
done

if [[ $drift_found -eq 0 ]]; then
    echo "✓ FFI shims in sync"
    exit 0
fi

if [[ $FIX_MODE -eq 1 ]]; then
    echo ""
    echo "✓ Regenerated. Review + commit:"
    echo "    git diff app/NextTerm/Generated/"
    exit 0
fi

echo ""
echo "error: FFI shim drift detected — see above" >&2
echo "fix: scripts/check-ffi-drift.sh --fix && git add app/NextTerm/Generated/" >&2
exit 1
