#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright © 2026 Zen Kiattikhunnawong

# Generate THIRD_PARTY_NOTICES.md (ADR-0007).
#
# Usage: scripts/gen-third-party-notices.sh [output-path]   (default: THIRD_PARTY_NOTICES.md)
#
# CI invocation: .github/workflows/ci.yml `rust-test` job regenerates to a temp
# path and diffs against the committed file, so a dependency bump that changes
# the notices cannot ship without the notices. It lives in that job rather than
# `custom-lints` because it needs the Rust toolchain and the crate sources cargo
# has already extracted.
#
# Scope: the crates cargo actually links into the app binary — `-e normal`
# drops build- and dev-dependencies (criterion and its tree never ship), and
# the workspace's own GPL crates are filtered out because this file is about
# what SolidTerm carries from others. The target is pinned to
# aarch64-apple-darwin, the only architecture app/project.yml builds, so the
# graph is the shipped one and the output is identical on any host.
#
# License texts are deduplicated by content: Apache-2.0 is one ~11 KB text
# shared by two dozen crates, and MIT texts that differ only by author are
# emitted per distinct text with every crate that ships it named above it.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

out="${1:-THIRD_PARTY_NOTICES.md}"
registry="${CARGO_HOME:-$HOME/.cargo}/registry/src"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

# name|version|license, workspace path-deps dropped, deduped, C-collated.
cargo tree -e normal -p solidterm-ffi --target aarch64-apple-darwin \
    --prefix none --format '{p}|{l}' \
    | sed 's/ (\*)$//' \
    | grep -v '(/' \
    | sed -E 's/^([^ ]+) v([^ |]+)( \(proc-macro\))?\|/\1|\2|/' \
    | LC_ALL=C sort -u > "$work/crates"

[ -s "$work/crates" ] || { echo "gen-third-party-notices: cargo tree returned nothing" >&2; exit 1; }

{
    echo "# Third-Party Notices"
    echo
    echo "SolidTerm is licensed GPL-3.0-or-later (see \`LICENSE\`). It links the Rust"
    echo "crates listed below, bundles the Swift runtime generated by swift-bridge, and"
    echo "ships theme palettes derived from the projects named at the end. Their license"
    echo "terms are reproduced here, as those terms require."
    echo
    echo "Generated by \`scripts/gen-third-party-notices.sh\` — do not edit by hand. CI"
    echo "regenerates it and fails when the committed copy has drifted."
    echo
    echo "## Rust crates linked into the binary"
    echo
    echo "| Crate | Version | License |"
    echo "| --- | --- | --- |"
    while IFS='|' read -r name version license; do
        echo "| $name | $version | $license |"
    done < "$work/crates"
    echo
} > "$work/out.md"

# Collect every license file each crate ships, keyed by content hash.
: > "$work/index"
: > "$work/notext"
while IFS='|' read -r name version license; do
    dir=$(ls -d "$registry"/*/"$name-$version" 2>/dev/null | LC_ALL=C sort | head -1) || true
    if [ -z "$dir" ]; then
        echo "gen-third-party-notices: no extracted source for $name $version" >&2
        echo "  expected under $registry/*/$name-$version — run 'cargo fetch' and a build first" >&2
        exit 1
    fi
    found=0
    while IFS= read -r file; do
        base=$(basename "$file")
        hash=$(shasum -a 256 "$file" | cut -d' ' -f1)
        [ -f "$work/text-$hash" ] || cp "$file" "$work/text-$hash"
        printf '%s|%s %s (%s)\n' "$hash" "$name" "$version" "$base" >> "$work/index"
        found=1
    done < <(find "$dir" -maxdepth 1 -type f \
        \( -iname 'LICENSE*' -o -iname 'LICENCE*' -o -iname 'COPYING*' -o -iname 'UNLICENSE*' -o -iname 'NOTICE*' \) \
        | LC_ALL=C sort)
    if [ "$found" -eq 0 ]; then
        printf '%s %s|%s\n' "$name" "$version" "$license" >> "$work/notext"
    fi
done < "$work/crates"

{
    echo "## License texts"
    echo
    echo "Each text below is reproduced once, followed by nothing else; the crates that"
    echo "ship that exact text are named above it."
    echo
} >> "$work/out.md"

# One block per distinct text, ordered by first appearance (crates are sorted).
awk -F'|' '!seen[$1]++ {print $1}' "$work/index" | while read -r hash; do
    {
        echo "### $(grep "^$hash|" "$work/index" | head -1 | cut -d'|' -f2-)"
        others=$(grep "^$hash|" "$work/index" | tail -n +2 | cut -d'|' -f2- | tr '\n' '|' | sed 's/|$//; s/|/, /g')
        if [ -n "$others" ]; then
            echo
            echo "Same text shipped by: $others"
        fi
        echo
        echo '```'
        cat "$work/text-$hash"
        echo '```'
        echo
    } >> "$work/out.md"
done

if [ -s "${work}/notext" ]; then
    {
        echo "### Crates that declare a license but ship no license file"
        echo
        echo "These crates carry a license expression in their manifest and no license"
        echo "text in the published package. The terms are the ones named here; the texts"
        echo "are the ones reproduced above for the sibling crate of the same project."
        echo
        echo "| Crate | License |"
        echo "| --- | --- |"
        while IFS='|' read -r crate license; do
            echo "| $crate | $license |"
        done < "$work/notext"
        echo
    } >> "$work/out.md"
fi

{
    echo "## swift-bridge generated Swift runtime"
    echo
    echo "\`app/SolidTerm/Generated/\` holds Swift and C sources emitted by swift-bridge"
    echo "at build time (\`app/scripts/build-rust.sh\`) and compiled into the app. They"
    echo "carry swift-bridge's own terms — Apache-2.0 OR MIT — whose texts appear above"
    echo "under the \`swift-bridge\` crate."
    echo
    echo "## Theme palettes"
    echo
    echo "Bundled themes under \`app/SolidTerm/Resources/Themes/\` whose colors come from"
    echo "another project. Each file names its origin on its first line. Themes drawn"
    echo "entirely for SolidTerm are not listed; one designed here but borrowing another"
    echo "project's ANSI ramp is, for the borrowed part."
    echo
    echo "| Theme | Palette | License | Upstream |"
    echo "| --- | --- | --- | --- |"
    for toml in $(LC_ALL=C ls app/SolidTerm/Resources/Themes/*.toml); do
        line=$(head -1 "$toml")
        case "$line" in "# Palette: "*) ;; *) continue ;; esac
        body=${line#\# Palette: }
        case "$body" in
            *" — "*) ;;
            # "SolidTerm original" and friends carry no upstream: nothing to
            # attribute, so they are not table rows. Anything else with a
            # "# Palette:" line but no " — " is a malformed attribution, and
            # silently dropping it would understate the notices.
            "SolidTerm original") continue ;;
            *)
                echo "gen-third-party-notices: $(basename "$theme"): unparseable palette line: $body" >&2
                exit 1
                ;;
        esac
        palette=${body% — *}
        terms=${body##* — }
        license=${terms%%,*}
        url=${terms#*, }
        echo "| $(basename "$toml") | $palette | $license | $url |"
    done
} >> "$work/out.md"

mkdir -p "$(dirname "$out")"
cp "$work/out.md" "$out"
echo "gen-third-party-notices: wrote $out ($(wc -l < "$out" | tr -d ' ') lines, $(wc -l < "$work/crates" | tr -d ' ') crates)"
